python:
  - "2.7"

script:
  - mkdir BUILD && doxygen doxyfile_options
  - |
    [ -z "`doxygen doxyfile_options 2>&1`" ]
  - make -C events/equeue test clean
  - PYTHONPATH=. python tools/test/config_test/config_test.py
  - PYTHONPATH=. python tools/test/build_api/build_api_test.py
  - PYTHONPATH=. python tools/test/targets/target_test.py
  - python tools/test/pylint.py
  - py.test tools/test/toolchains/api.py
  - python tools/test/memap/memap_test.py
  - python tools/project.py -S
  - python tools/build_travis.py
before_install:
  - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
  - sudo add-apt-repository -y ppa:libreoffice/libreoffice-4-2
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-arm-none-eabi doxygen --force-yes
  # Print versions we use
  - arm-none-eabi-gcc --version
  - python --version
  - doxygen --version
install:
  - sudo pip install -r requirements.txt
  - sudo pip install pytest
  - sudo pip install pylint
  - sudo pip install hypothesis
  - sudo pip install mock
